import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Toaster } from '@/components/ui/toaster';
import Navigation from '@/components/layout/Navigation';
import Footer from '@/components/Footer';
import { ErrorBoundary } from '@/components/ErrorBoundary';
import { Providers } from './providers'; // Import Providers
import { LoadingBar } from '@/components/LoadingBar';
import { ThemeProvider } from "@/components/theme/ThemeProvider";
import { SearchParamsWrapper } from '@/components/SearchParamsWrapper';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'zee_beady',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider>
          <ErrorBoundary>
            <Providers>
              <SearchParamsWrapper>
                <LoadingBar />
                <Navigation />
                <main className="min-h-screen">{children}</main>
                <Toaster />
                <Footer />
              </SearchParamsWrapper>
            </Providers>
          </ErrorBoundary>
        </ThemeProvider>
      </body>
    </html>
  );
}